"""auth

Revision ID: 5c72f33e6b82
Revises: fc081d95dc62
Create Date: 2022-01-21 11:24:39.457464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c72f33e6b82'
down_revision = 'fc081d95dc62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_type', sa.Enum('USER', 'GROUP', name='recipienttype'), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('obj_type', sa.Enum('SCHEMA', 'ENTITY', 'GROUP', name='permissiontargettype'), nullable=True),
    sa.Column('obj_id', sa.Integer(), nullable=True),
    sa.Column('permission', sa.Enum('SUPERUSER', 'USER_MANAGEMENT', 'CREATE_SCHEMA', 'UPDATE_SCHEMA', 'DELETE_SCHEMA', 'READ_SCHEMA', 'CREATE_ENTITY', 'UPDATE_ENTITY', 'DELETE_ENTITY', 'READ_ENTITY', name='permissiontype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipient_type', 'recipient_id', 'obj_type', 'obj_id', 'permission')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(length=128), nullable=True),
    sa.Column('lastname', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_groups')
    op.drop_table('users')
    op.drop_table('permissions')
    op.drop_table('groups')
    # ### end Alembic commands ###
