"""Add traceability tables and update others

Revision ID: 82f2152b4ec2
Revises: fc081d95dc62
Create Date: 2021-12-01 09:59:34.933611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '82f2152b4ec2'
down_revision = 'fc081d95dc62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DECLINED', 'APPROVED', name='changestatus'), nullable=False),
    sa.Column('change_object', sa.Enum('SCHEMA', 'ENTITY', name='changeobject'), nullable=False),
    sa.Column('change_type', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='changetype'), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("ALTER TYPE attrtype ADD value 'DATE' after 'DT';")
    attr_type = postgresql.ENUM('STR', 'BOOL', 'INT', 'FLOAT', 'FK', 'DT', 'DATE', name='attrtype', create_type=False)
    attr_type.create(op.get_bind())
    op.create_table('attr_create_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', attr_type, nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('unique', sa.Boolean(), nullable=False),
    sa.Column('list', sa.Boolean(), nullable=False),
    sa.Column('key', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('bind_to_schema', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bind_to_schema'], ['schemas.id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attr_delete_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attr_upd_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('new_name', sa.String(length=128), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('unique', sa.Boolean(), nullable=False),
    sa.Column('list', sa.Boolean(), nullable=False),
    sa.Column('key', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('bind_to_schema', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['bind_to_schema'], ['schemas.id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_create_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_update_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('new_name', sa.String(length=128), nullable=True),
    sa.Column('new_slug', sa.String(length=128), nullable=True),
    sa.Column('old_name', sa.String(length=128), nullable=True),
    sa.Column('old_slug', sa.String(length=128), nullable=True),
    sa.Column('new_deleted', sa.Boolean(), nullable=True),
    sa.Column('old_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schema_create_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('reviewable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schema_upd_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('new_name', sa.String(length=128), nullable=True),
    sa.Column('old_name', sa.String(length=128), nullable=True),
    sa.Column('new_slug', sa.String(length=128), nullable=True),
    sa.Column('old_slug', sa.String(length=128), nullable=True),
    sa.Column('new_reviewable', sa.Boolean(), nullable=True),
    sa.Column('old_reviewable', sa.Boolean(), nullable=True),
    sa.Column('new_deleted', sa.Boolean(), nullable=True),
    sa.Column('old_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('value_update_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('values_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Date(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_values_date_id'), 'values_date', ['id'], unique=False)
    op.add_column('schemas', sa.Column('reviewable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schemas', 'reviewable')
    op.drop_index(op.f('ix_values_date_id'), table_name='values_date')
    op.drop_table('values_date')
    op.drop_table('value_update_history')
    op.drop_table('schema_upd_history')
    op.drop_table('schema_create_history')
    op.drop_table('entity_update_history')
    op.drop_table('entity_create_history')
    op.drop_table('attr_upd_history')
    op.drop_table('attr_delete_history')
    op.drop_table('attr_create_history')
    op.drop_table('changes')
    op.drop_table('users')
    # ### end Alembic commands ###
