"""Update ChangeRequest table

Revision ID: d759fd3a1edc
Revises: 40157098b5ce
Create Date: 2021-12-28 17:31:05.156854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd759fd3a1edc'
down_revision = '40157098b5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_requests', sa.Column('object_type', sa.Enum('SCHEMA', 'ENTITY', name='changeobject'), nullable=False))
    op.add_column('change_requests', sa.Column('change_type', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='changetype'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_requests', 'change_type')
    op.drop_column('change_requests', 'object_type')
    # ### end Alembic commands ###
